name: Docker Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build docker
      run: |
        docker build -t tiancaige-voice-button .
        docker login --username=${{ secrets.ALIYUN_DOCKER_REGISTRY_EMAIL }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.ALIYUN_DOCKER_REGISTRY_PASSWORD }}
        docker tag tiancaige-voice-button:latest registry.cn-hangzhou.aliyuncs.com/fenyu-shine/tiancaige-voice-button:latest
        docker push registry.cn-hangzhou.aliyuncs.com/fenyu-shine/tiancaige-voice-button